services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: library_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: library_management
      MYSQL_USER: library_user
      MYSQL_PASSWORD: library_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - library_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Node.js Application
  app:
    build: .
    container_name: library_app
    restart: unless-stopped
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=library_user
      - DB_PASSWORD=library_password
      - DB_NAME=library_management
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
    networks:
      - library_network
    command: npm start

volumes:
  mysql_data:

networks:
  library_network:
    driver: bridge
